//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18444
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace cd2grprep.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=172.26.97.68;Initial Catalog=I3_IC;User Id=sa;Password=Iwatsu102;")]
        public string DBConnectString {
            get {
                return ((string)(this["DBConnectString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT CallEventLog,ConnectedDate,CallId,CallDurationSeconds,HoldDurationSeconds," +
            "CustomNum3 FROM dbo.CallDetail WITH (NOLOCK) WHERE I3TimeStampGmt >= @start AND " +
            "I3TimeStampGmt < @end")]
        public string SelectCallDetailSql {
            get {
                return ((string)(this["SelectCallDetailSql"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE dbo.IAgentQueueStats SET CustomValue1 = CustomValue1 + {3} WHERE dInterval" +
            "Start = \'{0}\' AND cName = \'{1}\' AND cReportGroup = \'{2}\' AND chKey3 = \'*\' AND ch" +
            "Key4 = \'*\';")]
        public string UpdateIAgentQueueStatsAll {
            get {
                return ((string)(this["UpdateIAgentQueueStatsAll"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UPDATE dbo.IAgentQueueStats SET CustomValue1 = CustomValue1 + {3} WHERE dInterval" +
            "Start = \'{0}\' AND cName = \'{1}\' AND cReportGroup = \'{2}\' AND ((chKey3 <> \'*\' AND" +
            " chKey4 = \'*\') OR (chKey3 <> \'*\' AND chKey4 = \'Call\') OR (chKey3 = \'*\' AND chKey" +
            "4 = \'*\'));")]
        public string UpdateIAgentQueueStatsNormal {
            get {
                return ((string)(this["UpdateIAgentQueueStatsNormal"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SELECT COUNT(*) FROM dbo.CallDetail WITH (NOLOCK) WHERE I3TimeStampGmt >= @start " +
            "AND I3TimeStampGmt < @end")]
        public string SelectCallDetailCountSql {
            get {
                return ((string)(this["SelectCallDetailCountSql"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int DBTimeOut {
            get {
                return ((int)(this["DBTimeOut"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int UpdateCommitCount {
            get {
                return ((int)(this["UpdateCommitCount"]));
            }
        }
    }
}
